<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="15.853" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2022-11-13T15:10:49" tests="0" file="cypress/e2e/secondTest.spec.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Test log out" timestamp="2022-11-13T15:10:49" tests="1" time="15.791" failures="1">
    <testcase name="Test log out Verify user can log out successfully" time="8.157" classname="Verify user can log out successfully">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign udp&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign udp'
    at Context.eval (webpack:///./cypress/e2e/secondTest.spec.js:9:30)]]></failure>
    </testcase>
  </testsuite>
</testsuites>